# Generated by Django 2.1.5 on 2019-02-23 01:54

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Volt', '0001_initial'),
        ('Volt', 'X0001_global_permissions'),
    ]
    operations = [
    ]
